name: setup-js-test

on:
  push:
    branches: ['**']

jobs:
  checks:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        lockfile-mode: ['with-lockfile', 'no-lockfile']
        package-manager: ['npm', 'yarn']
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create example package.json
        run: cp ./.artifacts/package-json ./package.json

      - name: Create example lockfile
        uses: actions/github-script@v6
        if: ${{ matrix.lockfile-mode == 'with-lockfile' }}
        with:
          script: |
            const { copyFileSync } = require('fs');

            if ('${{ matrix.package-manager }}' === 'yarn') {
              copyFileSync('./.artifacts/yarn-lock', './yarn.lock');
              return;
            }

            copyFileSync('./.artifacts/package-lock', './package-lock.json');

      - name: Setup and install
        uses: jedrzejginter/github-actions/setup-js@${{ github.sha }}
        id: setup
        with:
          package-manager: ${{ matrix.package-manager }}

      - name: Debug log
        uses: actions/github-script@v6
        with:
          script: console.log(${{ steps.setup.outputs.metadata-json-string }})
